[project]
name = "collaboration-svc"
version = "0.1.0"
description = "Collaboration Service for PeerPrep"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioredis[hiredis]>=2.0.1",
    "fastapi[standard]>=0.120.0",
]
